  #%RAML 0.8
---
title Sierra Madre API
baseUri: http://a365098.ngrok.com/api/{version}
version: v1
mediaType: application/json

/repositories:
  get:
  post:
/commits:
  get:
  post:
/fakes:
  get:
  post:

